---
jobs:
  - name: hm9000_z1
    instances: 0
  - name: hm9000_z2
    instances: 0

  - name: runner_z1
    instances: 0
  - name: runner_z2
    instances: 0

properties:
  cc:
    users_can_select_backend: false
    default_to_diego_backend: true
