#!/bin/bash

# Assuming you're using the kubernetes release from macosx:
# - brew install kubectl
# - kubectl config set-cluster furnace --insecure-skip-tls-verify=true --server=10.244.24.3:8080
# - kubectl config set-context furnace --cluster=furnace
# - kubectl config use-context furnace

# Verifying it deployed:
# - kubectl get services --namespace=kube-system
# - kubectl get rc --namespace=kube-system

tmpdir=$(mktemp -p -d registry-XXXXX)

cat >${tmpdir}/registry.yaml <<REGISTRY_EOF
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v0
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        emptyDir: {}
REGISTRY_EOF

cat >${tmpdir}/registry-service.yaml <<REGISTRY_SERVICE_EOF
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
REGISTRY_SERVICE_EOF

cat >${tmpdir}/registry-proxy.yaml <<REGISTRY_PROXY_EOF
apiVersion: v1
kind: Pod
metadata:
  name: kube-registry-proxy
  namespace: kube-system
spec:
  containers:
  - name: kube-registry-proxy
    image: gcr.io/google_containers/kube-registry-proxy:0.3
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
    env:
    - name: REGISTRY_HOST
      value: kube-registry.kube-system.svc.cluster.local
    - name: REGISTRY_PORT
      value: "5000"
    - name: FORWARD_PORT
      value: "5000"
    ports:
    - name: registry
      containerPort: 5000
      hostPort: 5000
REGISTRY_PROXY_EOF

kubectl create -f ${tmpdir}/registry.yaml
kubectl create -f ${tmpdir}/registry-service.yaml
kubectl create -f ${tmpdir}/registry-proxy.yaml
