#!/bin/bash

set -e -x -u
cd $GOPATH

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app github.com/cf-funace/k8s-nsync/cmd/nsync

  # gosub list \
  #     -test acceptance

} > /tmp/packages

cat /tmp/packages | xargs gosub sync
